---
- name: config
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items: 
    - "etc/openvpn/client.conf"
  notify: 
    - restart openvpn

